# Generated by Django 6.0.4 on 2026-07-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_colortheme_description_designstyle_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colortheme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designstyle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomsize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='description',
        ),
    ]
