# Generated by Django 6.0.4 on 2026-07-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='credits_granted',
            field=models.IntegerField(default=0, help_text='Number of credits added on purchase'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If True, user gets unlimited generations'),
        ),
    ]
