# Generated by Django 6.0.4 on 2026-04-18 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='uploads/rooms/')),
                ('num_samples', models.IntegerField(default=1)),
                ('prompt_used', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('color_theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.colortheme')),
                ('design_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.designstyle')),
                ('room_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.roomsize')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.roomtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='generation.generationjob')),
            ],
        ),
    ]
